# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: loli

release:
  github:
    owner: lpmatos
    name: loli
  name_template: "{{.ProjectName}}-v{{.Version}}"

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod download
    - go generate ./...

builds:
  - binary: loli
    id: loli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    mod_timestamp: '{{.CommitTimestamp}}'
    flags:
      - -trimpath
    ldflags:
     - -s -w -X "github.com/lpmatos/gen/internal/version.cliVersion={{.Env.CLIENT_VERSION}}" -X "github.com/lpmatos/gen/internal/version.builtDate={{.CommitDate}}" -X "github.com/lpmatos/gen/internal/version.builtBy=goreleaser" -X "github.com/lpmatos/gen/internal/version.commit={{.Commit}}" -X "github.com/lpmatos/gen/internal/version.commitShort={{.ShortCommit}}" -X "github.com/lpmatos/gen/internal/version.commitBranch={{.Env.GIT_BRANCH}}" -X "github.com/lpmatos/gen/internal/version.goVersion={{.Env.GO_VERSION}}"

checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'

changelog:
  skip: true

archives:
  - id: "loli"
    name_template: "{{.ProjectName}}_v{{.Version}}_{{.Os}}-{{.Arch}}"
    builds: [ "loli" ]
    format_overrides:
      - goos: windows
        format: zip
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

snapshot:
  name_template: "{{ .Tag }}-next"
