# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Loli < Formula
  desc ""
  homepage "https://github.com/ci-monk/loli"
  version "1.12.5"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ci-monk/loli/releases/download/v1.12.5/loli_v1.12.5_Darwin-arm64.tar.gz"
      sha256 "6aeea0326652b05f2a4d18fcecc258939b25dd172b54d36d421f79161903ca81"

      def install
        bin.install "loli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ci-monk/loli/releases/download/v1.12.5/loli_v1.12.5_Darwin-x86_64.tar.gz"
      sha256 "43eb0bfcd3ff9e905f344f4826bececd8c854965c774383b151248101fccbeb4"

      def install
        bin.install "loli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ci-monk/loli/releases/download/v1.12.5/loli_v1.12.5_Linux-arm64.tar.gz"
      sha256 "97efa43faf19deda3d1fced4bbc839447305a994ce122acb1baa712bac6cf982"

      def install
        bin.install "loli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ci-monk/loli/releases/download/v1.12.5/loli_v1.12.5_Linux-x86_64.tar.gz"
      sha256 "416df17bf0705265da862a43b9f0ab96b9bdc6b59fe87a58a6acfe0993a5655f"

      def install
        bin.install "loli"
      end
    end
  end
end
